        ########################################################
        #                                                      # 
        #   Home Occupancy Binary Sensor                       #
        #                                                      # 
        ########################################################

#binary_sensor:
  #- platform: template
   # sensors:
   #   home_occupancy:
    #    value_template: {{ is_state('group.occupancy', 'home') }}
      #  name: Home Occupancy Sensor