        ########################################################
        #                                                      # 
        #   Uptime Robot Binary Sensor                         #
        #                                                      # 
        ########################################################

binary_sensor:
  - platform: uptimerobot
    api_key: !secret uptimebot