input_datetime:

        ########################################################
        #                                                      # 
        #   Boiler's Last Run Time                             #
        #                                                      # 
        ########################################################

  boiler_last_runtime:
    name: Last Duration
    has_time: true
    has_date: false


input_boolean:
  boiler_status:
    name: Boiler Status