binary_sensor:

        ########################################################
        #                                                      # 
        #   Washing Machine's Power On/Off sensor              #
        #                                                      # 
        ########################################################

  - platform: template
    sensors:
      washing_machine_on:
        friendly_name: Washing Machine On
        delay_off:
            minutes: 5
        value_template: >
            {{ states('sensor.shellyem_d3b358_0_power') | float > 5 }}

  - platform: template
    sensors:
      dryer_on:
        friendly_name: Dryer On
        delay_off:
            minutes: 5
        value_template: >
            {{ states('sensor.shellyem_d3b358_1_power') | float > 1000 }}

