# sensor:
#         ########################################################
#         #                                                      # 
#         #   Sonarr                                             #
#         #                                                      # 
#         ########################################################
      
#   - platform: sonarr
#     api_key: !secret sonarr_api
#     host: 192.168.1.X
#     port: 8989