# switch:
#       - platform: template
#         switches:

#           switcher_webapi:
#               friendly_name: Swithcer Boiler
#               icon_template: mdi:shower
#               entity_id: sensor.switcher_webapi
#               value_template: "{{ is_state_attr('sensor.switcher_webapi', 'state', 'on') }}"
#               turn_on:
#                   service: script.turn_on
#                   data:
#                     entity_id: script.switcher_turn_on
#               turn_off:
#                   service: script.turn_on
#                   data:
#                     entity_id: script.switcher_turn_off