#Close fridge door
- id: 'Close fridge door'
  description: TTS when Fridge door has been left open
  trigger:
  - platform: state
    entity_id: binary_sensor.openclose_29
    from: 'off'
    to: 'on'
    for: 00:00:25
  condition: []
  action:
  - service: tts.google_translate_say
    data: 
      entity_id: media_player.living_room_speaker
      message: Please close The Refrigerator door.
  mode: single