########################################
#                                      #
#     Notify about boiler set off      #
#                                      #
########################################

- id: '1579304142734'
  alias: Boiler Is OFF
  description: ''
  trigger:
  - entity_id: switch.boiler
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data_template:
      message: 'Boiler is now: {{trigger.to_state.state}} '
      title: Boiler Status has changed!
    service: notify.mobile_app_dor

########################################
#                                      #
#     Update Boiler's run time         #
#                                      #
########################################
- alias: boiler_run_time
  trigger:
  - platform: time_pattern
    minutes: /1
  action:
  - service: homeassistant.update_entity
    entity_id: sensor.boiler_run_time
  id: b6168b8aa2284124bc5c79d14f8ead7f



########################################
#                                      #
#     Send Telegram Messgae about      #
#     Boiler been Turned ON            #
#                                      #
########################################
- id: '1584895251093'
  alias: Notify when Boiler is ON
  trigger:
  - entity_id: switch.boiler
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: person.dor
      state: home
  action:
  - data:
      inline_keyboard:
      - Leave On:/leaveon, Turn OFF:/turnoff, Turn OFF Later:/later
      message: Boiler has been turn ON, Wnat to do?
    service: telegram_bot.send_message
  mode: single

########################################
#                                      #
#     Turn Boiler OFF with Telegram    #
#                                      #
########################################
- id: '1584896502370'
  alias: Turn OFF Boiler By Notification
  description: ''
  trigger:
  - event_data:
      command: /turnoff
    event_type: telegram_callback
    platform: event
  condition: []
  action:
  - data:
      chat_id: 343154522
      message_id: last
    service: telegram_bot.delete_message
  - entity_id: switch.boiler
    service: switch.turn_off
  - data:
      message: OK,Turning OFF Boiler.
    service: telegram_bot.send_message

########################################
#                                      #
#     Turn Boiler OFF with Timer       #
#     Via Telegram                     #
#                                      #
########################################
- id: '1584896502377'
  alias: Turn OFF Boiler With Timer By Notification
  description: ''
  trigger:
  - event_data:
      command: /later
    event_type: telegram_callback
    platform: event
  condition: []
  action:
  - data:
      chat_id: 343154522
      message_id: last
    service: telegram_bot.delete_message
  - data:
      inline_keyboard:
      - 15 Mins:/15mins, 20 Mins:/20mins, 30 Mins:/30mins
      message: Okay, How long should I wait?
    service: telegram_bot.send_message
- id: '1584896502387'
  alias: Set Boiler Timer for 15 mins By TelegramBot
  description: ''
  trigger:
  - event_data:
      data: /15mins
    event_type: telegram_callback
    platform: event
  condition: []
  action:
  - data:
      chat_id: 343154522
      message_id: last
    service: telegram_bot.delete_message
  - data_template:
      message: Okay, Turning OFF boiler in 15 mins
    service: telegram_bot.send_message
  - delay: 00:15:00
  - entity_id: switch.boiler
    service: switch.turn_off

########################################
#                                      #
#     Set Boiler's Timer               #
#     With Telegram                    #
#                                      #
########################################
# 20 MINS
- id: '1584896502320'
  alias: Set Boiler Timer for 20 mins By TelegramBot
  description: ''
  trigger:
  - event_data:
      data: /20mins
    event_type: telegram_callback
    platform: event
  condition: []
  action:
  - data:
      chat_id: 343154522
      message_id: last
    service: telegram_bot.delete_message
  - data_template:
      message: Okay, Turning OFF boiler in 20 mins
    service: telegram_bot.send_message
  - delay: 00:20:00
  - entity_id: switch.boiler
    service: switch.turn_off
# 30 MINS
- id: '1584896502330'
  alias: Set Boiler Timer for 30 mins By TelegramBot
  description: ''
  trigger:
  - event_data:
      data: /30mins
    event_type: telegram_callback
    platform: event
  condition: []
  action:
  - data:
      chat_id: 343154522
      message_id: last
    service: telegram_bot.delete_message
  - data_template:
      message: Okay, Turning OFF boiler in 30 mins
    service: telegram_bot.send_message
  - delay: 00:30:00
  - entity_id: switch.boiler
    service: switch.turn_off


########################################
#                                      #
#     Set Boiler's Last Run time       #
#                                      #
########################################
- id: '15875347433466'
  alias: Boiler Last Run Time
  trigger:
  - entity_id: switch.boiler
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.boiler_last_runtime
    data_template:
      time: '{{ (as_timestamp(now())-as_timestamp(states.input_boolean.boiler_status.last_changed))
        | timestamp_custom(''%H:%M:%S'', False) }}'
  initial_state: 'on'

########################################
#                                      #
#     Toggle boiler Input_boolean      #
#                                      #
########################################
- id: 'Toggle input_boolean.boiler_status'
  description: ''
  trigger:
  - platform: state
    entity_id: switch.boiler
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: switch.boiler
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.boiler_status
  mode: single

########################################
#                                      #
#     Notify About Boiler Beening      #
#     on for more than 1hr             #
#                                      #
########################################
- id: '1609315377262'
  alias: Notify when Boiler is ON for more than an hour
  description: ''
  trigger:
  - platform: state
    entity_id: switch.boiler
    from: 'off'
    to: 'on'
    for: 01:01:00
  condition:
  - condition: state
    entity_id: person.dor
    state: home
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room_speaker
      message: Heads up, Boiler has been ON for more than an hour. Water's temperature is '{{ states.sensor.boiler_water_tempature.state }}' degress
  - condition: not
    conditions:
    - condition: state
      entity_id: person.dor
      state: home
  - service: notify.ha_bot
    data:
      message: The Boiler has been ON for more than an hour now...
  mode: single

########################################
#                                      #
#     Turn OFF boiler when running     #
#     On a timer script                #
#                                      #
########################################
- id: '1609921350037'
  alias: Turn OFF boiler on Script Stop
  description: ''
  trigger:
  - platform: state
    entity_id: script.1587736515086
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: script.1587736564493
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: script.1579361301301
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.boiler
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.boiler
  mode: single

########################################
#                                      #
#     Daily Time for Boiler            #
#                                      #
########################################
- id: '1612369633225'
  alias: Daily Boiler Timer
  description: ''
  trigger:
  - platform: time
    at: '17:20'
  condition:
  - condition: numeric_state
    entity_id: sensor.boiler_water_tempature
    below: '30'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.boiler
  - delay: 02:00:00
  - service: switch.turn_off
    data: {}
    entity_id: switch.boiler
  mode: single