########################################
#                                      #
#     Dryer Automations                #
#                                      #
########################################


- alias: dryer_run_time_update
  trigger:
  - platform: time_pattern
    minutes: /1
  action:
  - service: homeassistant.update_entity
    entity_id: sensor.dryer_run_time
  id: d218db5452f943afa8db53e40a0de553


#TTS When Dryer has finished
- id: '1587024142299'
  alias: TTS When Dryer has finished
  description: ''
  trigger:
  - entity_id: binary_sensor.dryer_on
    for: 00:03:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: media_player.living_room_speaker
      message: The dryer, has finished.
    service: tts.google_translate_say
  mode: single

#Dryer Last Run Time
- id: '15875347433455'
  alias: Dryer Last Run Time
  trigger:
  - entity_id: binary_sensor.dryer_on
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.dryer_full
  - service: input_datetime.set_datetime
    entity_id: input_datetime.dryer_last_runtime
    data_template:
      time: '{{ (as_timestamp(now())-as_timestamp(states.switch.dryer_end.last_changed))
        | timestamp_custom(''%H:%M:%S'', False) }}'
  - service: input_datetime.set_datetime
    entity_id: input_datetime.dryer_end_date
    data_template:
      time: '{{ as_timestamp(now()) | timestamp_custom(''%H:%M:%S'', True) }}

        '
      date: '{{ as_timestamp(now()) | timestamp_custom(''%Y-%m-%d'', True) }}

        '
  initial_state: 'on'

#Toggle dryer_end
- id: '1589283780312'
  alias: Toggle dryer_end
  description: ''
  trigger:
  - entity_id: binary_sensor.dryer_on
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: switch.dryer_end
    service: switch.toggle

#Dryer Boolean OFF
- id: 'Dryer Boolean OFF'
  alias: Dryer Boolean OFF
  description: Sets input_boolean.dryer_full to OFF
  trigger:
  - platform: state
    entity_id: binary_sensor.openclose_26
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.dryer_full
    state: 'on'
  action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.dryer_full
  mode: single

#TTS reminder of dryer
- id: 'TTS reminder of dryer'
  alias: 'TTS reminder of dryer '
  description: 'TTS on google home a reminder after 15mins which the luandry is still in the dryer'
  trigger:
  - platform: state
    entity_id: input_boolean.dryer_full
    from: 'off'
    to: 'on'
    for: 00:15:00
  condition:
  - condition: state
    entity_id: person.dor
    state: home
  action:
  - service: tts.google_translate_say
    data:
      message: Yo! The laundry is still in the dryer!
      entity_id: media_player.living_room_speaker
  mode: single

#Notify Dor about laundry still in the dryer
- id: 'Notify Dor about laundry still in the dryer'
  alias: Notify Dor about laundry still in the dryer
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.dryer_full
    from: 'off'
    to: 'on'
    for: 00:15:00
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: person.dor
      state: home
  action:
  - service: notify.mobile_app_dor
    data:
      title: Laundry in the Dryer
      message: The Dryer has finished 15 mins ago, laundry's still in
  mode: single

#Remind dor of laundry in the dryer when coming back home
- id: 'Remind dor of laundry in the dryer when coming back home'
  alias: Remind dor of laundry in the dryer when coming back home
  description: ''
  trigger:
  - platform: state
    entity_id: person.dor
    to: home
    for: 00:03:00
    from: away
  condition:
  - condition: state
    entity_id: input_boolean.dryer_full
    state: 'on'
  action:
  - service: tts.google_translate_say
    data:
      message: Hey Dor, theres laundry in the dryer. Better take it out.
      entity_id: media_player.living_room_speaker
  mode: single

#LED Green light when dryer is full
- id: 'LED Green light when dryer is full'
  alias: LED Green light when dryer is full
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.dryer_full
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.fastled_ws2811_light
      brightness: 255
      color_name: green
  mode: single

#LED light OFF when dryer is empty
- id: 'LED light OFF when dryer is empty'
  alias: LED light OFF when dryer is empty
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.dryer_full
    to: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: light.fastled_ws2811_light
  mode: single