########################################
#                                      #
#     Yard's Gate Automations          #
#                                      #
########################################

- id: '1581960646902'
  alias: notify when the gate's open
  description: ''
  trigger:
  - entity_id: binary_sensor.yard_gate
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: person.dor
      state: home
  action:
  - data:
      message: who was it??
      title: Gate has been opened!
    service: notify.mobile_app_dor
  mode: single
- id: '1583255533917'
  alias: TTS when gate's open
  description: ''
  trigger:
  - entity_id: binary_sensor.yard_gate
    for: 00:00:02
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.dor
    state: home
  - after: 07:00
    before: '20:30'
    condition: time
  action:
  - data:
      volume_level: 0.4
    entity_id: media_player.living_room_speaker
    service: media_player.volume_set
  - data:
      entity_id: media_player.living_room_speaker
      message: The gate, has been opened
    service: tts.google_translate_say
