########################################
#                                      #
#     Washing Machine Automations      #
#                                      #
########################################

- alias: sensor.washing_machine_run_time
  trigger:
  - platform: time_pattern
    minutes: /1
  action:
  - service: homeassistant.update_entity
    entity_id: sensor.washing_machine_run_time
  id: f48ab9263a9b43efa513c88a10b985ff

# TTS When Laundry is finished 
- id: '1587021582299'
  alias: TTS When Laundry is finished
  description: ''
  trigger:
  - entity_id: binary_sensor.washing_machine_on
    for: 00:03:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: media_player.living_room_speaker
      message: Laundy is finished.
    service: tts.google_translate_say
  - data:
      message: just now!
      title: laundry is finished
    service: notify.mobile_app_dor

# Washing Machine Last Run Time
- id: '15875347433444'
  alias: Washing Machine Last Run Time
  trigger:
  - entity_id: binary_sensor.washing_machine_on
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.washing_machine_full
  - service: input_datetime.set_datetime
    entity_id: input_datetime.washing_machine_last_runtime
    data_template:
      time: '{{ (as_timestamp(now())-as_timestamp(states.switch.wm_end.last_changed))
        | timestamp_custom(''%H:%M:%S'', False) }}'
  - service: input_boolean.turn_on
    entity_id: input_boolean.washing_machine_full
  - service: input_datetime.set_datetime
    entity_id: input_datetime.wm_end_date
    data_template:
      time: '{{ as_timestamp(now()) | timestamp_custom(''%H:%M:%S'', True) }}

        '
      date: '{{ as_timestamp(now()) | timestamp_custom(''%Y-%m-%d'', True) }}

        '
  initial_state: 'on'



- id: '1589284019780'
  alias: Toggle wm_end
  description: ''
  trigger:
  - entity_id: binary_sensor.washing_machine_on
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: switch.wm_end
    service: switch.toggle

# Washing Machine Boolean OFF
- id: '1609526681850'
  alias: Washing Machine Boolean OFF
  description: Sets input.boolean_washing_machine_finished to OFF
  trigger:
  - platform: state
    entity_id: binary_sensor.washing_machine_door
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.washing_machine_full
    state: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.washing_machine_full
  mode: single

# TTS reminder of laundry
- id: '1609526958589'
  alias: 'TTS reminder of laundry'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.washing_machine_full
    from: 'off'
    to: 'on'
    for: 00:15:00
  condition:
  - condition: state
    entity_id: person.dor
    state: home
  action:
  - service: tts.google_translate_say
    data:
      message: Hey, looks like you forgot the laundry. Better get it out.
      entity_id: media_player.living_room_speaker
  mode: single

# Notify Dor about laundry still in the machine
- id: '1609527502037'
  alias: Notify Dor about laundry still in the machine
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.washing_machine_full
    from: 'off'
    to: 'on'
    for: 00:15:00
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: person.dor
      state: home
  action:
  - service: notify.mobile_app_dor
    data:
      title: Laundry in the machine
      message: Washing machine had finished 15 mins ago, laundry's still in
  mode: single

# Remind dor of laundry in the washing machine when coming back home
- id: '1609527736156'
  alias: Remind dor of laundry in the washing machine when coming back home
  description: ''
  trigger:
  - platform: state
    entity_id: person.dor
    to: home
    for: 00:03:00
    from: away
  condition:
  - condition: state
    entity_id: input_boolean.washing_machine_full
    state: 'on'
  action:
  - service: tts.google_translate_say
    data:
      message: Hey Dor, theres laundry in the machine. Better take it out.
      entity_id: media_player.living_room_speaker
  mode: single


# LED Blue light when washing machine is full
- id: 'LED Blue light when washing machine is full'
  alias: LED Blue light when washing machine is full
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.washing_machine_full
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.fastled_ws2811_light
      brightness: 255
      color_name: blue
  mode: single

# LED light OFF when washing machine is empty
- id: 'LED light OFF when washing machine is empty'
  alias: LED light OFF when washing machine is empty
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.washing_machine_full
    to: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: light.fastled_ws2811_light
  mode: single