switch:
  - platform: broadlink
    mac: !secret broadlink_mac
    switches:
      ########################################################
      #                                                      #
      #   Living Room RC Control                             #
      #                                                      #
      ########################################################

      - name: Play Radio
        command_on: "JgBYAAABKJYSExI4ExMSOBI4EjgTNxIUEjgSExI4ExMSExMTEhMSOBM3EhQSExM3EhMTExITEhMSFBI4EzcSFBI4EjgTNxIUEgAFSAABJ0sSAAxoAAEnTBEADQU="

      - name: HDMI2
        command_on: "JgBQAAABJ5YTEhM3EhQSOBI4EzcTOBITEjgSFBI4ExISExMTEhMSOBIVETgTEhI4ExMSExI4EhQSOBMSEzcSFBI4EjgSFBITEgAFSAABKEsTAA0FAAAAAAAAAAA"
        command_off: "JgBQAAABJ5YTEhM3EhQSOBI4EzcTOBITEjgSFBI4ExISExMTEhMSOBIVETgTEhI4ExMSExI4EhQSOBMSEzcSFBI4EjgSFBITEgAFSAABKEsTAA0FAAAAAAAAAAA"

      - name: HDMI1
        command_on: "JgBYAAABKJUSFBI4ExISORI4EzcTNxIUEjgSExM3EhQTEhITEhQTNxM3EzcSORITExISFBI4EhMTExITExISOBM4EjgTEhIUEgAFSAABJ0wRAAxoAAEnTBIADQU="
        command_off: "JgBYAAABKJUSFBI4ExISORI4EzcTNxIUEjgSExM3EhQTEhITEhQTNxM3EzcSORITExISFBI4EhMTExITExISOBM4EjgTEhIUEgAFSAABJ0wRAAxoAAEnTBIADQU="

      - name: TV ON OFF
        command_on: "JgDSAJOWETkSOBI4EhMSExITEhMSExI4EzcSOREUERQRFBITERQRFBE5EhMSExMSExISExITEjgSExI4EjkRORE5EzcSOBIABgSTlRI4EjgTOBITEhMRFBEUEhMSOBI4EjgSExMSExISExITEhMTNxQRExMRFBITERQRFBE5ERQSOBM3EzcSOBI4EjkRAAYEk5YSOBI4EjgSExITExISExITEjgSOBI5ERQRFBEUERQRFBEUEjgTEhMSEhMSExITEhMTNxITEjkRORI4EjgSOBI4EgANBQAAAAAAAA=="
        command_off: "JgDSAJOWETkSOBI4EhMSExITEhMSExI4EzcSOREUERQRFBITERQRFBE5EhMSExMSExISExITEjgSExI4EjkRORE5EzcSOBIABgSTlRI4EjgTOBITEhMRFBEUEhMSOBI4EjgSExMSExISExITEhMTNxQRExMRFBITERQRFBE5ERQSOBM3EzcSOBI4EjkRAAYEk5YSOBI4EjgSExITExISExITEjgSOBI5ERQRFBEUERQRFBEUEjgTEhMSEhMSExITEhMTNxITEjkRORI4EjgSOBI4EgANBQAAAAAAAA=="

      - name: rc_vol_down
        command_on: "JgBYAAABKJUTExI4EhMSORI4EzcTNxMTEjgTEhM3EhQTEhITEhQTNxM3EjgTExI4EjgSFBEUEhMSFBEUEzcSExMTEzcTNxI4EgAFIwABKEwRAAxoAAEnTBIADQU="
        command_off: "JgBYAAABKJUTExI4EhMSORI4EzcTNxMTEjgTEhM3EhQTEhITEhQTNxM3EjgTExI4EjgSFBEUEhMSFBEUEzcSExMTEzcTNxI4EgAFIwABKEwRAAxoAAEnTBIADQU="

      - name: rc_vol_up
        command_on: "JgBYAAABKJYRFBI4ExITOBM3EzcTNxIUEjgSExI5ERQSExMTERQSOBMSEzgSExI4EjgTExITEhMSORITEzcTExEUEzcTNxM3EgAFIwABKEsSAAxoAAEnTBIADQU=="
        command_off: "JgBYAAABKJYRFBI4ExITOBM3EzcTNxIUEjgSExI5ERQSExMTERQSOBMSEzgSExI4EjgTExITEhMSORITEzcTExEUEzcTNxM3EgAFIwABKEsSAAxoAAEnTBIADQU=="

      - name: rc_mute
        command_on: "JgBQAAABJ5YTEhI4EhQTNxI4EjgSORITEjgSFBI4EhMSFBEUEhMSOBIUEhMSOBM4ETkSExITEhQSOBI4ExMSExITEzcTOBI4EwAFIgABJ0wTAA0FAAAAAAAAAAA="
        command_off: "JgBQAAABJ5YTEhI4EhQTNxI4EjgSORITEjgSFBI4EhMSFBEUEhMSOBIUEhMSOBM4ETkSExITEhQSOBI4ExMSExITEzcTOBI4EwAFIgABJ0wTAA0FAAAAAAAAAAA="

      - name: RC ON OFF
        command_on: "JgBYAAABKZQUEhQ2FDYUNhQ2FTYUNhQRFDYVERQRFBIUERQRFBIUNhQRFDYUEhQ2FBEUNhQSFBEUNhQSFDYUERQ2FBIUNhQ2FAAFIQABKUoUAAxlAAEqSRQADQU="
        command_off: "JgBYAAABKZQUEhQ2FDYUNhQ2FTYUNhQRFDYVERQRFBIUERQRFBIUNhQRFDYUEhQ2FBEUNhQSFBEUNhQSFDYUERQ2FBIUNhQ2FAAFIQABKUoUAAxlAAEqSRQADQU="
