        ########################################################
        #                                                      # 
        #   Gas Ballon's Weight setting                        #
        #                                                      # 
        ########################################################


input_number:
  left_gas_ballon_weight:
    name: Left Gas Ballon Weight
    min: 1
    max: 20
    step: 0.10
    mode: box
    icon: 'mdi:gas-cylinder'
    unit_of_measurement: kg



  right_gas_ballon_weight:
    name: Right Gas Ballon Weight
    min: 1
    max: 20
    step: 0.10
    mode: box
    icon: 'mdi:gas-cylinder'
    unit_of_measurement: kg